# Generated by Django 5.0.6 on 2025-09-22 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('link', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partage',
            name='mode_partage',
            field=models.TextField(),
        ),
    ]
