# Generated by Django 5.0.6 on 2025-10-23 10:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('link', '0002_alter_partage_mode_partage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Apercu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo_profil', models.ImageField(blank=True, null=True, upload_to='apercu_photos/', verbose_name='Photo de profil')),
                ('nom_affichage', models.CharField(max_length=100, verbose_name='Nom à afficher')),
                ('profil', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='apercu', to='link.profil', verbose_name='Profil associé')),
            ],
            options={
                'verbose_name': 'Aperçu',
                'verbose_name_plural': 'Aperçus',
            },
        ),
    ]
