# Generated by Django 5.0.6 on 2025-10-23 10:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('link', '0003_apercu'),
    ]

    operations = [
        migrations.CreateModel(
            name='LienApercu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordre_affichage', models.IntegerField(default=0)),
                ('est_actif', models.BooleanField(default=True)),
                ('apercu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='link.apercu')),
                ('lien', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='link.lien')),
            ],
            options={
                'ordering': ['ordre_affichage'],
            },
        ),
        migrations.AddField(
            model_name='apercu',
            name='liens',
            field=models.ManyToManyField(blank=True, related_name='apercus', through='link.LienApercu', to='link.lien', verbose_name="Liens de l'aperçu"),
        ),
        migrations.AddConstraint(
            model_name='lienapercu',
            constraint=models.CheckConstraint(check=models.Q(('ordre_affichage__gte', 0), ('ordre_affichage__lte', 5)), name='ordre_affichage_0_a_5'),
        ),
    ]
